[ConnManager]
Port=23200

[Machines]
ActiveW=Strato-Dummy

[ActiveW]
MaterialsDB=hmi
Options=full-auto,speed-coeff:100,send-error-perc:0,do-not-promote-dummy-guest
; Available machine options:
;    auto-start (emulated machine - start work on step synchronization)
;    full-auto (emulated machine - work automatically the next step automatically)
;    show-shape (emulated machine - show generated shape gcode)
;    send-error-perc (emulated machine - error probability of project synchronization)
;    speed-coeff:<perc> (emulated machine - emulated time coefficient percentage)
;    do-not-promote-dummy-guest (emulated machine - treat as a normal machine)

EventsLog=$(YYYY-MM) $(machine-name) events.csv
;EventSinks=tcp-json://localhost:9999
NotifyEventsToSubscribers=true
