[MaterialsDB]
File=materials.ini
SaveOnEdit=false

[GUI]
Lang=it
ColorDiff=20

[ConnManager]
Port=23200

[Machines]
ActiveW=Strato-Dummy
StarCut=Float-Dummy

[ActiveW]
;MaterialsDB=trust-hmi
PrintMode=request-client;serve-myself;skip
;Printer=default
;CanBuildProject=true

; Available machine options:
;    sloppy (be more error tolerant)
;    send-all-schemes-at-once (transmit to machine all scheme files on project send)
;    conn-touts:<send ms>/<recv ms> (millisecond timeout of send and receive)
;    udf-version:compact (specify m32 udf syntax)
;    gcode:<optimizepaths,...> (options passed to G-code generator)
;    auto-start (emulated machine - start work on step synchronization)
;    full-auto (emulated machine - work automatically the next step automatically)
;    show-shape (emulated machine - show generated shape gcode)
;    send-error-perc (emulated machine - error probability of project synchronization)
;    speed-coeff:<perc> (emulated machine - emulated time coefficient percentage)
;    do-not-promote-dummy-guest (emulated machine - treat as a normal machine)
Options=speed-coeff:200,send-error-perc:2,gcode:optimizepaths

; Available shape options:
;    convert-to-genshape (convert polygonal shapes to generic)
;    flip-polygonals (mirror horizontally any polygonal shape)
;    send-single-genshape (in case of a single generic shape, send directly instead of using MacoHmi)
;    skip-genshapes (ignore generic shapes, do not work them)
Shapes=convert-to-genshape,flip-polygonals,send-single-genshape

;WorkHistoryLog=C:\Macotec\Logs\$(machine-name)\$(YYYY) work.json
;EventsLog=C:\Macotec\Logs\$(machine-name)\$(YYYY-MM) events.csv
NotifyEventsToSubscribers=true


[StarCut]
; Available machine options:
;    sloppy (be more tolerant to errors)
;    send-all-schemes-at-once (transmit to machine all scheme files on project send)
;    conn-touts:<send ms>/<recv ms> (millisecond timeout of send and receive)
;    tpf-max-length:<mm> (float machine: cut to limit the length of removed tpf)
;    no-stripes-data (float machine: don't send additional udf data)
;    auto-start (emulated machine: start work on step synchronization)
;    send-error-perc (emulated machine - error probability of project synchronization)
Options=tpf-max-length:2500
